# Generated by Django 4.2.16 on 2024-12-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="avatar",
            new_name="avatar_url",
        ),
    ]
